Vagrant.configure("2") do |config|
    config.vm.synced_folder "./configs", "/vagrant_shared"

    config.vm.define "mboyS" do |master|
      master.vm.hostname = "mboyS"
      master.vm.provider "virtualbox" do |vb|
        vb.name = "mboyS"
        vb.memory = 1024
        vb.cpus = 2
      end
  
      master.vm.box = "bento/debian-12"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provision "shell", path: "./scripts/master.sh", args: ['192.168.56.110']
    end
  end
