RAM = 1024
CPU = 1

Vagrant.configure("2") do |config| 
  config.vm.synced_folder "./configs", "/vagrant_shared"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end
  config.vm.define "mla-rosaS" do |master|
    master.vm.hostname = "mla-rosaS"
      master.vm.provider "virtualbox" do |v|
        v.memory = RAM
        v.cpus = CPU
    end
    master.vm.box = "bento/debian-12"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provision "shell", path: "./scripts/master.sh", args: ['192.168.56.110']
  end
  config.vm.define "mla-rosaSW" do |worker|
    worker.vm.hostname = "mla-rosaSW"
    worker.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
    worker.vm.box = "bento/debian-12"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "./scripts/worker.sh", args: ['192.168.56.110']
  end
end